<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\EasyProblems\_53_MaxSubArray.cs" Link="_53_MaxSubArray.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ConsoleMe\src\ConsoleMe\ConsoleMe.csproj" />
  </ItemGroup>

</Project>
